### ISSUE TITLE
Write tox moderniser for Django 4.2 support

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/repo-tools#389]
## Description
Create tox moderniser script to add testing support for Django 4.2 tests. 

```[tasklist]
### Tasks
- [x] Create a new folder `django42` under `edx_repo_tools/codemods` folder
- [x] Add a new `tox_moderniser_djanog42` script
- [x] Do test run of the script on an example repo
```
