### ISSUE TITLE
Write Github Actions moderniser for Django 4.2 support

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/repo-tools#390]
## Description 
Create GitHub Actions moderniser script to add testing support for Django 4.2 in the CI workflows.

```[tasklist]
### Tasks
- [x] Create a new script `github_actions_moderniser` under `edx_repo_tools/codemods/django42`
- [x] Script should be able to update `toxenv` section in the `ci.yml` file and include `django42` in it
- [x] Script should also check and update the coverage checks to run with `django42` where applicable
- [x] Test the script on an example repo
```
