### ISSUE TITLE
Repo Checks: Users should not have direct repo access

### ISSUE THREAD

**Issue by kdmccormick** [openedx/repo-tools#407]
Background: All repo access should go through teams, as it makes it saner for us to establish and manage an access stucture for the org. Most repo access goes through teams today, although some repos give direct access to people.

```[tasklist]
### Tasks
- [ ] Write a repo checks that flags & removes all users who are directly added to any given repo.
- [ ] Dry-run the check. Looks at the list of direct-user-repo access. Are some of those access grants appropriate?
- [ ] Where it's appropriate: Move the users into teams (creating teams as necessary) which grant the same access.
- [ ] Run the check again, this time with `--no-dry-run`, which should remove all remaining users with direct repo access.
```

**Comment by kdmccormick** [comment]
Note: this could be based on the `EnsureNoMaintainOrAdmin` check, which Feanil recently added: https://github.com/openedx/repo-tools/blob/9434beab752ab0ea3f5c8e454f0eaeb75f617de7/edx_repo_tools/repo_checks/repo_checks.py#L160

**Comment by farhan** [comment]
@kdmccormick Thanks for creating the well-groomed story. I have the following question

"Should admin users be candidates to be removed as well?"

**Comment by kdmccormick** [comment]
@farhan Yep, no user should be directy on a repo with any level of access.

**Comment by feanil** [comment]
I've run this check on the org and made all the necessary updates.
